### ISSUE TITLE
Telescope user script -> not showing Telescope report for APAC customers

### ISSUE THREAD

**Issue by korinapieters** [tuxfre/esko-SC-scripts#7] opened 2016-03-14 08:32 UTC
# Esko SC Script issue
## Steps to reproduce the issue:
1. Go to TBP, tab 'Worldwide'
2. Go to customer CAHAYA
3. Go to Telescope report -> you see that there is a TeleScope report on TBP
4. Go to ServiceCloud, case 586182 (for customer CAHAYA)
5. No telescope status is shown
## Other details:

The Telescope link refers to : 
http://begesesgf001.esko-graphics.com/CS-Customers-SystemInfo-Gent/CAHAYA/systeminfo/html/Most_Recent.html
Maybe there is a change needed in the 'SystemInfo-Gent' part? Could you explore the TBP Telescope link?

Thx,
Korina

**Comment by tuxfre** [comment] 2016-03-14 11:24
Hi @korinapieters,

I agree, this is something I overlooked regarding telescope.

I'd need to know how many location we have for the data. I also think your suggestion in [issue 5](https://github.com/tuxfre/esko-SC-scripts/issues/4) is the best way to go.

I'm going to close this one as duplicate and we can continue there as this is a duplicate of #5

**Closed as completed by tuxfre** 2016-03-14 11:24 UTC
Labels: bug, duplicate, scripts/Telescope Status
